### ISSUE TITLE
Calling clear in terminal causes exception

### ISSUE THREAD

**Issue by avivace** [Wramberg/TerminalView#43]
* debian unstable
* ST3 3142

typing `clear` crashes TerminalView:

```
Exception in thread Thread-853:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "TerminalView in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 118, in _main_update_loop
  File "TerminalView in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 146, in _poll_shell_output
  File "sublime_terminal_buffer in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 69, in insert_data
  File "terminal_emulator in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 25, in feed
  File "pyte.streams in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 378, in feed
  File "pyte.streams in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 166, in feed
  File "pyte.streams in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 315, in _parser_fsm
  File "pyte.streams in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 215, in dispatch
  File "terminal_emulator in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 134, in erase_in_display
  File "pyte.screens in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 995, in erase_in_display
  File "pyte.screens in /home/avivace/.config/sublime-text-3/Installed Packages/TerminalView.sublime-package", line 688, in erase_in_display
UnboundLocalError: local variable 'interval' referenced before assignment
```

**Comment by Wramberg** [comment]
Please provide the information requested in the issue template

* OS used
* Bash version
* Arguments being used with the terminal_view_open command
* A dump of the environment vars from the terminal view (call env in the terminal inside ST3)
*  Anything else you can think of that might help

Calling clear in the terminal works fine for me.

**Comment by rwols** [comment]
I cannot reproduce this on macOS 10.12 neither with bash 3.2 nor with bash 4.4.

**Comment by Wramberg** [comment]
It probably due to wrong `TERM` variable. But no way to know before we get some more information :-)

**Comment by bfelder** [comment]
Linux Mint 18.2, bash reporting in: 
No crash with clear in TerminalView.

**Comment by avivace** [comment]
My bad, I was calling fish from bashrc, no crash operating normally.
