### ISSUE TITLE
Open Bash Terminal results in frozen terminal with blinking cursor

### ISSUE THREAD

**Issue by mandeep** [Wramberg/TerminalView#64]
OS: Debian 9 (Gnome 3 DE)
Bash version: GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)

With the 0.5.0 release, when I select Open Bash Terminal from the command palette, a terminal window opens showing only a blinking cursor. The prior release worked fine. Let me know if there's anything else I can add to help.

**Comment by mandeep** [comment]
Changing ``terminal_view_show_colors`` from true to false results in a working terminal. Changing this setting back to true also seems to work.

**Comment by Wramberg** [comment]
So you cannot reproduce this ? I'm thinking maybe the upgrade messed something up which required an ST3 restart to be fixed.

**Comment by nchursin** [comment]
I have the same problem, using zsh. Switching back to bash did nothing, so did color switching off/on. Let me know if I can help with this

**Comment by Wramberg** [comment]
When this happens your probably have an exception in the sublime text console. Would be great if you could dump that.

**Comment by nchursin** [comment]
Sure, here it is.
```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "sublime_terminal_buffer in /Users/nchursin/Library/Application Support/Sublime Text 3/Installed Packages/TerminalView.sublime-package", line 320, in run
TypeError: log() missing 1 required positional argument: 'string'
Exception in thread Thread-14942:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "TerminalView in /Users/nchursin/Library/Application Support/Sublime Text 3/Installed Packages/TerminalView.sublime-package", line 174, in _main_update_loop
  File "TerminalView in /Users/nchursin/Library/Application Support/Sublime Text 3/Installed Packages/TerminalView.sublime-package", line 221, in _resize_screen_if_needed
TypeError: log() missing 1 required positional argument: 'string'```

**Comment by rwols** [comment]
Could you print your env variables from within sublime? Open the console, (the actual console, not a TerminalView), then **open a new buffer**, and then type this in the console:
```
>>> import os
>>> import json
>>> view.run_command("append", {"characters": json.dumps(dict(os.environ), indent=2)})
```

**Comment by nchursin** [comment]
```
{
  "LOGNAME": "nchursin", 
  "XPC_FLAGS": "0x0", 
  "SHELL": "/bin/zsh", 
  "Apple_PubSub_Socket_Render": "/private/tmp/com.apple.launchd.8WxYXXL6EZ/Render", 
  "DISPLAY": "/private/tmp/com.apple.launchd.JgszMdX6cy/org.macosforge.xquartz:0", 
  "SECURITYSESSIONID": "186a6", 
  "COMMAND_MODE": "unix2003", 
  "TMPDIR": "/var/folders/pd/rxlrj2y5647cb4nldgq6hvtr0000gn/T/", 
  "USER": "nchursin", 
  "PATH": "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin", 
  "XPC_SERVICE_NAME": "com.apple.xpc.launchd.oneshot.0x10000006.Sublime Text", 
  "HOME": "/Users/nchursin", 
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.cehLnvGjX6/Listeners", 
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0"
}
```

**Comment by rwols** [comment]
Are you using the system bash (3.2) in /usr/bin or the brew bash (4.4) in /usr/local/bin?

**Comment by nchursin** [comment]
I think it's 4.4 launching by default. At least it runs when I invoke `bash`.

**Comment by infocortex** [comment]
I was able to resolve this by closing all files/windows and relaunching Sublime. Toggling settings did not work for me.

**Comment by mandeep** [comment]
@Wramberg I am able to reproduce this by uninstalling TerminalView and reinstalling it via Package Control. However, it does seem that a restart of Sublime fixes the problem.

**Comment by nchursin** [comment]
Closing everything helped. Just really didn't want to do that 😃 
Seems like Sublime needs feature like on VS Code - reload current workspace)

**Comment by Wramberg** [comment]
Thanks for all the info guys 👍 
Im very busy these days but as soon as I have some time I'll look into this.
